# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5d9413d6538fc521f82caf8cc2aa50abb6b4d97347838e73232496d931fa30b90bff4fe104e4744e5f4566b6c6ed866647deb1a3cdc846a4bbb437cfe99180a

test:
  secret_key_base: d53ec9fca11d637cf8c226cc120104a2494ddab4c46fe123a1f52305e5799ff3eba0f5d9db4de66a40a36982328fe57a19ccd6d2da71f6347b6e196e9d11bcb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
